server:
  port: 20001
spring:
  application:
    name: nanyiba-payment-consul-consumer
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://210.22.22.150:3269/nanyiba-springcloudalibaba-payment?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  cloud:
    ##############consul注册中心################################
    consul:
      port: 8500
      host: 134.175.104.248
      discovery:
        #对外暴露的服务
        service-name: ${spring.application.name}
        heartbeat:
          enabled: true
    ##############consul注册中心################################
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
